export const PAST = [
    'were adopted by a blood cult',
    'barely survived traumatic relationship',
    'are a murderer on the run',
    'were a victim of identity theft',
    'lost something important',
    'suffer from a family curse',
    'are part of a damning conspiracy',
    'lost an easy, well-paying government job',
    'were voluenteered for an experimental brain transplant',
    'spent five years in coma',
    'enjoyed peaceful life, suddenly interrupted by tragedy',
    'were clinically dead for 5 minutes',
];

export const REASON = [
    'you suffer from a rare illness and a need insurance',
    'have a family to support',
    'you have very low self-esteem; this is all you deserve',
    'your parents said this is what success looks like',
    'the office is close to home',
    'of the free coffee',
    'of your twisted need for an oppressive structure, like at home',
    'your weird fetish for suits',
    'your lack of ideas for a career',
    'you dream of a stable career',
    'you\'re an absolute psychopath',
    'of your submissive personality',
    'need to belong to <strong>SOMETHING</strong>',
    'of a nightmarish curse',
    'you owe a huge debt to some scary people',
    'you\'re on an espionage mission for a rival corp',
    'of cronyism, you haven\'t earned this',
    'of soul-crushing boredom',
    'of a recommendation by a supposed friend',
    'you made a grave mistake'
];

export const YEARNING = [
    'enough money to solve your problems',
    'power to make them <strong>FEAR</strong> you',
    'safety from whatever hunts you',
    'so much blood, more than anyone can imagine',
    'the thrill of adrenaline pumping through your veins',
    'the freedom to do whatever your dark heart desires',
    'forbidden knowledge that only this place can provide',
    'fulfilment by being part of winning team',
    'success that comes at the cost of others',
    'to belong to something greater than yourself',
    'the transformation that comes with work',
    'the extreme exaltation after barely making it though the workday',
    'to feel love for the first time',
    'to escape the horrors of the world and find peace within your work',
    'pleasure; material, monetary, or otherwise',
    'to experience the inter-office drama you\'ve seen on tv',
    'pain so pure that it wipes your sins clean',
    'the purity of performing a task to the letter',
    'to lose yourself in your work and go numb',
    'absolution in the form of labor',
];

export const STRESS = [
    'bite your nails until your fingertips are bloody stumps',
    'soak yourself with sweat',
    'breakout in extreme rashes',
    'yank fistfuls of your hair out',
    'scratch angry red furrows into your skin',
    'turn a lurid red',
    'get blood boilingly angry',
    'wail like banshee',
    'go completely catatonic',
    'clench your jaws so hard your teeth crack',
    'carve lines into yourself',
    'isolate yourself in the nearest, smallest space',
    'bite your lips bloody',
    'feel intense and passionate arousal',
    'stutter like a machine gun',
    'clench your chest as your heart palpatates worryingly ',
    'burst into roaring flames',
    'cry and sob uncontrollably',
    'fall over in narcoleptic slumber',
    'do not care. Stress simply doesn\'t affect you',
];

export const JOBS = [
    {
        name: 'helpdesker',
        descrip: "<strong>You\'re the first one to take the hit.</strong> Not because you can necessarily endure it, but because they needed some <strong>cannon fodder</strong>. If you made it alive so far, maybe there is something more in you. <strong>“Once broken, a bone heals back stronger”</strong> after all.",
        skill_descrips: [
            'The stress of handling customer complaints gave you two of these:',
            'Each time, after taking a first hit in a fight:'
        ],
        first_skill: [
            'Loss of vision in one eye <strong>(but opened a third one?)</strong>',
            'Panic attacks <strong>(that brings visions of the future?)</strong>',
            'Constant heartburn <strong>(literal?)</strong>',
            'Tinnitus <strong>(sounds like… speech?)</strong>',
            'Weight loss <strong>(can you get into the vent now?)</strong>',
            'Insomnia <strong>(only restore d4 HP after rest)</strong>',
        ],
        second_skill: [
            'Adrenaline kicks in, <strong>gain a free counter-attack</strong>',
            'Your skin, muscles, and bones toughen, <strong>add -d2 armor for d4 rounds</strong>',
            'Pain makes you stronger, <strong>+1 damage for d6 rounds</strong>',
            '<strong>Reality shifts:</strong> mitigate all damage and teleport randomly in a 10 meter radius',
            'Black flames explode around you, <strong>damaging yourself and every enemy in sight for d4 damage</strong>',
            'Attacker becomes overwhelmed by guilt looking at your miserable face, <strong>test their Motivation (lowered by 2)</strong>',
        ],
    },
    {
        name: 'salesperson',
        descrip: "They said you could sell sand to desert dwellers. Silvertongued, <strong>you easily manipulate others</strong>, so they agreed on whatever bullshit you had to offer. All it took was some bad luck and one month below the target. <strong>Now, you have nothing to lose and everything to gain.</strong>",
        skill_descrips: [
            'You are selling:',
            'Once a day, you can choose to use the following tactic:'
        ],
        first_skill: [
            'Blood of stray animals.',
            'Human bones.',
            'Sentient ticks.',
            'Insight-bestowing eyes.',
            'The scent of non-existing flowers.',
            'Something called “Coins of the Two-Headed Hybrid.”',
        ],
        second_skill: [
            '<strong>Foot in the Door.</strong> Both during and outside of battle, you can ask for something small (napkin, penny etc.) followed by a bigger request (for one to kill themselves, attack a friend, surrender, etc.). The first ask will be automatically successful. In the following round, test Soft Skills DR16 for the second ask.',
            '<strong>Long Pitch.</strong> Start pitching. Doesn\'t matter what you say, just try to get people to listen. All enemies skip their action.',
            '<strong>Discount.</strong> Loot an additional d66x10¤ from the fallen enemy.',
            '<strong>Door-in-the-face.</strong> Ask someone for something big. Test their Motivation and Soft Skills DR12. If both tests are successful, the target will do what they were asked to do.',
            '<strong>Understanding Pain Points.</strong> Analyze an enemy. Skip one turn. Next turn, you deal +d6 damage to the analyzed opponent.',
            '<strong>FOMO (Fear of Misplaced Omens).</strong> Harness the fear of your enemies by offering them a limited deal (e.g., run now or be brutally violated later). Test their Motivation this turn.'
        ],
    }
];

export const NAMES = [
    'Jonn',
    'Gene',
    'Jane',
    'Mikael',
    'Sussan',
    'Dave ID',
    'Emi',
    'Robby',
    'Sarha ',
    'Karren',
    'Lindy',
    'Willyam',
    'Pathricia',
    'Nanncy',
    'Marvy',
    'Loura',
    'Sammsy',
    'Barbrry',
    'Dantel',
    'Debr’ah',
    'Thommy',
    'Ama',
    'Brayn',
    'Stepph',
    'Cyntya',
    'Edd W.',
    'Charles III ',
    'Miquelle',
    'Jeff',
    'Rebby',
    'Coxy',
    'Scotchy',
    'Kamilla',
    'Justina',
    'Ravy',
    'Chin',
    'Meloras',
    'Yooki',
    'Sorra',
    'Himeshi',
    'Taro',
    'Lin',
    'Ayya',
    'H. Akira',
    'Yong',
    'Ha Na',
    'Aruto',
    'Shiy',
    'Ahmmy',
    'Hass',
    'Nouhr',
    'Ali B.',
    'Mohha',
    'Yuss',
    'Ranya',
    'Lima',
    'Dallya',
    'Ariq',
    'Freq',
    'Janush',
    'Pille',
    'Pike',
    'Mourav',
    'Gracyan',
    'Edemyon',
    'Alamina',
    'Bozena',
    'Loyza',
]